services:
  - type: web
    name: my-django-blog
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      # Install Playwright and download Chromium
      pip install playwright
      playwright install chromium --with-deps
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn lms_project.wsgi:application --bind 0.0.0.0:$PORT
    releaseCommand: python manage.py migrate
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        value: "<your-secret-key>"
      - key: ALLOWED_HOSTS
        value: "my-django-blog.onrender.com"
    autoDeploy: true
    healthCheckPath: /
    disk: 512

envVars:
  - key: DJANGO_DEBUG
    value: "False"
  - key: DJANGO_SECRET_KEY
    value: "<your-secret-key>"
  - key: ALLOWED_HOSTS
    value: "my-django-blog.onrender.com"

  # ADD THESE ðŸ‘‡
  - key: DJANGO_SUPERUSER_USERNAME
    value: "admin"
  - key: DJANGO_SUPERUSER_EMAIL
    value: "admin@myblog.com"
  - key: DJANGO_SUPERUSER_PASSWORD
    value: "StrongAdmin@123"
